[package]
name = "pombase-gocam"
version = "0.9.0"
edition = "2021"
rust-version = "1.84"

[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
anyhow = "1.0"
phf = { version = "0.11.3", features = ["macros"] }
